# Generated by Django 4.1.1 on 2022-09-07 16:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('cpf', models.IntegerField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('croptype', models.CharField(max_length=10)),
                ('harvestdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('lossevent', models.CharField(max_length=20)),
            ],
        ),
    ]
