# Generated by Django 4.1.1 on 2022-09-07 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_communication_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
