# Generated by Django 4.1.1 on 2022-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_communication_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
